/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Controllers.HoaDonCTController;
import Controllers.HoaDonController;
import Controllers.KhachHangController;
import Controllers.LoaiSanPhamController;
import Controllers.NhanVienController;
import Controllers.SanPhamController;
import Extentions.Check;
import Models.HoaDon;
import Models.HoaDonCT;
import Models.KhachHang;
import Models.LoaiSanPham;
import Models.NhanVien;
import Models.SanPham;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author DuyNguyen
 */
public class QLHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form QLHoaDon
     */
    private List<HoaDon> hoadon;
    private List<SanPham> sanpham;
    private List<LoaiSanPham> loaisanpham;
    private DefaultTableModel modelHD;  //Tạo model cho JTable
    private DefaultTableModel modelSP;
    private DefaultTableModel modelSPCT;
    private DefaultComboBoxModel modelLSP;
    int selectedIndex;

    // Bonus
    private ArrayList<SanPham> gioHang;
    private ArrayList<NhanVien> listNV;
    private ArrayList<KhachHang> listKH;

    public QLHoaDon() {
        initComponents();
        AutoCompleteDecorator.decorate(cmbKhachHang);
        AutoCompleteDecorator.decorate(cmbNhanVien);

        // Bonus
        gioHang = new ArrayList<>();
        sanpham = new SanPhamController().getlistSP();
        loaisanpham = new LoaiSanPhamController().getlistSP();
                
        listNV = new NhanVienController().getListStaff();
        DefaultComboBoxModel modelNV = new DefaultComboBoxModel();
        for (NhanVien nv : listNV) {
            modelNV.addElement(nv);
        }
        cmbNhanVien.setModel(modelNV);

        listKH = new KhachHangController().getList();
        DefaultComboBoxModel modelKH = new DefaultComboBoxModel();
        for (KhachHang kh : listKH) {
            modelKH.addElement(kh);
        }
        cmbKhachHang.setModel(modelKH);
        
        loaisanpham = new LoaiSanPhamController().getlistSP();
        modelLSP = new DefaultComboBoxModel();
        for (LoaiSanPham lsp : loaisanpham) {
            modelLSP.addElement(lsp);
        }
        ComboboxType.setModel(modelLSP);
        // End Bonus

        this.setLocationRelativeTo(null);
        modelHD = (DefaultTableModel) TableHoadon.getModel();
        modelSP = (DefaultTableModel) TableSP.getModel();
        modelSPCT = (DefaultTableModel) TableSPCT.getModel();
        showTableHD();
        showTableSP();
        showCart();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbKhachHang = new javax.swing.JComboBox<>();
        cmbNhanVien = new javax.swing.JComboBox<>();
        txtTenNhanVien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMasp = new javax.swing.JTextField();
        txtTensp = new javax.swing.JTextField();
        ComboboxType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSP = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableSPCT = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableHoadon = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        btnAddHd = new javax.swing.JButton();
        btnAddSp = new javax.swing.JButton();
        btnDeleteHd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnDeleteSPCT = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_bill.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ ĐƠN HÀNG");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Tên khách hàng:");

        jLabel3.setText("Số điện thoại:");

        jLabel13.setText("Mã nhân viên:");

        cmbKhachHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKhachHangActionPerformed(evt);
            }
        });

        cmbNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNhanVienActionPerformed(evt);
            }
        });

        txtTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNhanVienActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên Nhân Viên:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbKhachHang, 0, 142, Short.MAX_VALUE)
                    .addComponent(cmbNhanVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenNhanVien)
                    .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Mã sản phẩm:");

        jLabel7.setText("Tên sản phẩm:");

        ComboboxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboboxTypeActionPerformed(evt);
            }
        });

        jLabel8.setText("Loại:");

        jLabel9.setText("Số lượng:");

        jLabel10.setText("Giá:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTensp)))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ComboboxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboboxType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        TableSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Loại", "Số lượng", "Giá/1 sản phẩm"
            }
        ));
        TableSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSP);
        if (TableSP.getColumnModel().getColumnCount() > 0) {
            TableSP.getColumnModel().getColumn(0).setMaxWidth(40);
            TableSP.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_table.png"))); // NOI18N
        jLabel11.setText("Bảng sản phẩm");

        TableSPCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane2.setViewportView(TableSPCT);
        if (TableSPCT.getColumnModel().getColumnCount() > 0) {
            TableSPCT.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_grocery-cart.png"))); // NOI18N
        jLabel12.setText("Giỏ hàng");

        TableHoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Ngày đặt", "Thành tiền"
            }
        ));
        TableHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableHoadonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TableHoadon);
        if (TableHoadon.getColumnModel().getColumnCount() > 0) {
            TableHoadon.getColumnModel().getColumn(0).setMaxWidth(50);
            TableHoadon.getColumnModel().getColumn(1).setMaxWidth(200);
        }

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_table.png"))); // NOI18N
        jLabel16.setText("Bảng hóa đơn");

        btnAddHd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddHd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        btnAddHd.setText("Refesh");
        btnAddHd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddHdActionPerformed(evt);
            }
        });

        btnAddSp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAddSp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add to basket.png"))); // NOI18N
        btnAddSp.setText("Thêm vào giỏ hàng");
        btnAddSp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSpActionPerformed(evt);
            }
        });

        btnDeleteHd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteHd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        btnDeleteHd.setText("Xóa hóa đơn");
        btnDeleteHd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHdActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btnSave.setText("Thêm hóa đơn");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        jButton1.setText("THOÁT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDeleteSPCT.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDeleteSPCT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        btnDeleteSPCT.setText("Xóa sản phẩm giỏ hàng");
        btnDeleteSPCT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSPCTActionPerformed(evt);
            }
        });

        btnDetail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDetail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Task list.png"))); // NOI18N
        btnDetail.setText("Xem chi tiết hóa đơn");
        btnDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddSp)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteSPCT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteHd)
                        .addGap(18, 18, 18)
                        .addComponent(btnDetail)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddHd))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(355, 355, 355)
                                .addComponent(jLabel1))
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddHd)
                    .addComponent(btnAddSp)
                    .addComponent(btnDeleteHd)
                    .addComponent(btnSave)
                    .addComponent(btnDeleteSPCT)
                    .addComponent(btnDetail))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // OK
    private void btnAddSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSpActionPerformed
        // TODO add your handling code here:
        selectedIndex = TableSP.getSelectedRow();

        if (selectedIndex == -1 || txtMasp.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Hãy chọn sản phẩm để thêm vào giỏ hàng!", "Lỗi", JOptionPane.WARNING_MESSAGE);
        } else {
            String soLuongStr = txtSoluong.getText();

            if (new Check().isDigit(soLuongStr)) {
                int soLuong = Integer.parseInt(soLuongStr.trim());
                SanPham sp = new SanPham();
                sp = sanpham.get(selectedIndex);

                if (soLuong < 1) {
                    JOptionPane.showMessageDialog(this, "Số lượng sản phẩm phải lớn hơn 0!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                } else if (soLuong > sp.getSoLuong()) {
                    JOptionPane.showMessageDialog(this, "Số lượng sản phẩm vượt quá số lượng đang có hiện tại!", "Lỗi", JOptionPane.WARNING_MESSAGE);
                } else {
                    sp.setSoLuong(soLuong);
                    sp.setGia(Integer.parseInt(txtGia.getText())*soLuong);
                    gioHang.add(sp);
                    showCart();
                    refesh();
                }

            } else {
                JOptionPane.showMessageDialog(this, "Số lượng sản phẩm không hợp lệ!", "Lỗi", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAddSpActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String date = simpleDateFormat.format(new Date());

        if (txtSDT.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Hãy nhập đầy đủ thông tin cần thiết!", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        } else if (gioHang.size() == 0) {
            JOptionPane.showMessageDialog(this, "Giỏ hàng đang trống!", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            HoaDon hd = new HoaDon();
            ArrayList<HoaDonCT> listHDCT = new ArrayList<>();

            Object kh = cmbKhachHang.getSelectedItem();
            Object nv = cmbNhanVien.getSelectedItem();

            hd.setIDKhachHang(((KhachHang) kh).getID());
            hd.setIDNhanVien(((NhanVien) nv).getID());
            hd.setNgayLap(date);

            int gia = 0;
            for (SanPham sp : gioHang) {
                gia += sp.getGia();
            }
            hd.setThanhTien(gia);

            int IDHoaDon = new HoaDonController().AddHD(hd);

            for (SanPham sp : gioHang) {
                HoaDonCT hdct = new HoaDonCT();
                hdct.setIDHoaDon(IDHoaDon);
                hdct.setIDSanPham(sp.getID());
                hdct.setSoLuong(sp.getSoLuong());
                hdct.setTenSanPham(sp.getTenSanPham());
                hdct.setGia(sp.getGia() / sp.getSoLuong());
                listHDCT.add(hdct);
            }

            new HoaDonCTController().Add(listHDCT);
            JOptionPane.showMessageDialog(this, "Đã tạo thành công đơn hàng!", "Thành công", JOptionPane.INFORMATION_MESSAGE);

            new SanPhamController().UpdateQuantity(listHDCT);
            gioHang.clear();
            showTableSP();
            showCart();
            showTableHD();
            refesh();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Home home = new Home();
        home.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddHdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddHdActionPerformed
        // TODO add your handling code here:
        refesh();
    }//GEN-LAST:event_btnAddHdActionPerformed

    // OK
    private void TableSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSPMouseClicked
        // TODO add your handling code here:
        selectedIndex = TableSP.getSelectedRow();
        SanPham sp = sanpham.get(selectedIndex);
        txtMasp.setText(sp.getMaSanPham());
        txtTensp.setText(sp.getTenSanPham());
        
        LoaiSanPham lsp = new LoaiSanPhamController().GetById(sp.getIDLoaiSanPham());
        int index = 0;
        int size = loaisanpham.size();
        for (int i = 0; i < size; i++) {
            if(loaisanpham.get(i).getID() == lsp.getID()){
                index = i;
            }
        }  
        ComboboxType.setSelectedIndex(index);
        
        txtGia.setText(sp.getGia() + "");
    }//GEN-LAST:event_TableSPMouseClicked

    // OK
    private void btnDeleteHdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHdActionPerformed
        selectedIndex = TableHoadon.getSelectedRow();
        if (hoadon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu để xóa!", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        } else if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 dòng rồi xóa", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            HoaDon hd = hoadon.get(selectedIndex);
            new HoaDonController().DeleteHD(hd.getID());
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            showTableHD();
            refesh();
        }
    }//GEN-LAST:event_btnDeleteHdActionPerformed

    private void btnDeleteSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSPCTActionPerformed
        // TODO add your handling code here:
        selectedIndex = TableSPCT.getSelectedRow();

        if (gioHang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không có dữ liệu để xóa!", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        } else if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn 1 dòng rồi xóa", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            gioHang.remove(selectedIndex);
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            showCart();
            refesh();
        }
    }//GEN-LAST:event_btnDeleteSPCTActionPerformed

    // OK
    private void cmbKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKhachHangActionPerformed
        // TODO add your handling code here:
        Object obj = cmbKhachHang.getSelectedItem();
        txtSDT.setText(((KhachHang) obj).getSDT());
    }//GEN-LAST:event_cmbKhachHangActionPerformed

    private void TableHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableHoadonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TableHoadonMouseClicked

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        // TODO add your handling code here:
        selectedIndex = TableHoadon.getSelectedRow();
        if (hoadon.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Danh sách hóa đơn rỗng!", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        } else if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn hóa đơn mà bạn cần xem!", "Lỗi", JOptionPane.INFORMATION_MESSAGE);
        } else {
            HoaDon hd = hoadon.get(selectedIndex);
            this.dispose();
            QLHoaDonCT qlHDCT = new QLHoaDonCT(hd, true);
            qlHDCT.setVisible(true);
        }
    }//GEN-LAST:event_btnDetailActionPerformed

    private void txtTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNhanVienActionPerformed

    private void cmbNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNhanVienActionPerformed
        // TODO add your handling code here:
        Object obj = cmbNhanVien.getSelectedItem();
        txtTenNhanVien.setText(((NhanVien) obj).getTenNhanVien());
    }//GEN-LAST:event_cmbNhanVienActionPerformed

    private void ComboboxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboboxTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboboxTypeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHoaDon.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHoaDon.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHoaDon.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHoaDon.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboboxType;
    private javax.swing.JTable TableHoadon;
    private javax.swing.JTable TableSP;
    private javax.swing.JTable TableSPCT;
    private javax.swing.JButton btnAddHd;
    private javax.swing.JButton btnAddSp;
    private javax.swing.JButton btnDeleteHd;
    private javax.swing.JButton btnDeleteSPCT;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbKhachHang;
    private javax.swing.JComboBox<String> cmbNhanVien;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMasp;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTensp;
    // End of variables declaration//GEN-END:variables

    private void showTableHD() {
        hoadon = new HoaDonController().getlistHD();
        modelHD.setRowCount(0);
        for (HoaDon hd : hoadon) {
            modelHD.addRow(new Object[]{
                TableHoadon.getRowCount() + 1, hd.getID(), hd.getNgayLap(), hd.getThanhTien()
            });
        }
    }

    // OK
    private void showTableSP() {
        sanpham = new SanPhamController().getlistSP();
        modelSP.setRowCount(0);
        for (SanPham hd : sanpham) {
            if (hd.getSoLuong() > 0) {
                LoaiSanPham lsp = new LoaiSanPhamController().GetById(hd.getIDLoaiSanPham());
                modelSP.addRow(new Object[]{
                    TableSP.getRowCount() + 1, hd.getMaSanPham(), hd.getTenSanPham(), lsp.getTenLoaiSanPham(), hd.getSoLuong(), hd.getGia()
                });
            }
        }
    }

    // Ok
    private void showCart() {
        modelSPCT.setRowCount(0);
        for (SanPham sp : gioHang) {
            modelSPCT.addRow(new Object[]{
                TableSPCT.getRowCount() + 1,
                sp.getMaSanPham(),
                sp.getTenSanPham(),
                sp.getSoLuong(),
                sp.getGia() / sp.getSoLuong(),
                sp.getGia()
            });
        }
    }

    private void refesh() {
        txtSDT.setText("");
        txtMasp.setText("");
        txtTensp.setText("");
        txtSoluong.setText("");
        txtGia.setText("");
        ComboboxType.setSelectedIndex(0);
    }
}
